name: CI - Python Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  python-lint-and-type-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install Poetry
      run: |
        pipx install poetry

    - name: Install poetry dependencies
      run: make install 

    - name: Run ruff
      run: |
        poetry run ruff check .
        poetry run ruff format --check

    - name: Run mypy
      run: poetry run mypy -p lens
